package com.example.chinesechesstrainning.support;

import com.example.chinesechesstrainning.R;
import com.example.chinesechesstrainning.model.Piece;

public class Support {

    public static void setPieceDefault(Piece piece){
        piece.setDead(false);
        switch ((int) piece.getId()){
            case 1: piece.setCurrent_col(9);
                piece.setCurrent_row(7);
                piece.setImage(R.drawable.red_soldier);
                piece.setClickedAndMovedImage(R.drawable.red_soldier_move);
                break;
            case 2: piece.setCurrent_col(7);
                piece.setCurrent_row(7);
                piece.setImage(R.drawable.red_soldier);
                piece.setClickedAndMovedImage(R.drawable.red_soldier_move);
                break;
            case 3: piece.setCurrent_col(5);
                piece.setCurrent_row(7);
                piece.setImage(R.drawable.red_soldier);
                piece.setClickedAndMovedImage(R.drawable.red_soldier_move);
                break;
            case 4: piece.setCurrent_col(3);
                piece.setCurrent_row(7);
                piece.setImage(R.drawable.red_soldier);
                piece.setClickedAndMovedImage(R.drawable.red_soldier_move);
                break;
            case 5: piece.setCurrent_col(1);
                piece.setCurrent_row(7);
                piece.setImage(R.drawable.red_soldier);
                piece.setClickedAndMovedImage(R.drawable.red_soldier_move);
                break;

            case 6: piece.setCurrent_col(8);
                piece.setCurrent_row(8);
                piece.setImage(R.drawable.red_cannon);
                piece.setClickedAndMovedImage(R.drawable.red_cannon_move);
                break;
            case 7: piece.setCurrent_col(2);
                piece.setCurrent_row(8);
                piece.setImage(R.drawable.red_cannon);
                piece.setClickedAndMovedImage(R.drawable.red_cannon_move);
                break;
            case 8: piece.setCurrent_col(9);
                piece.setCurrent_row(10);
                piece.setImage(R.drawable.red_chariot);
                piece.setClickedAndMovedImage(R.drawable.red_chariot_move);
                break;
            case 9: piece.setCurrent_col(1);
                piece.setCurrent_row(10);
                piece.setImage(R.drawable.red_chariot);
                piece.setClickedAndMovedImage(R.drawable.red_chariot_move);
                break;
            case 10: piece.setCurrent_col(8);
                piece.setCurrent_row(10);
                piece.setImage(R.drawable.red_horse);
                piece.setClickedAndMovedImage(R.drawable.red_horse_move);
                break;
            case 11: piece.setCurrent_col(2);
                piece.setCurrent_row(10);
                piece.setImage(R.drawable.red_horse);
                piece.setClickedAndMovedImage(R.drawable.red_horse_move);
                break;
            case 12: piece.setCurrent_col(7);
                piece.setCurrent_row(10);
                piece.setImage(R.drawable.red_elephant);
                piece.setClickedAndMovedImage(R.drawable.red_elephant_move);
                break;
            case 13: piece.setCurrent_col(3);
                piece.setCurrent_row(10);
                piece.setImage(R.drawable.red_elephant);
                piece.setClickedAndMovedImage(R.drawable.red_elephant_move);
                break;
            case 14: piece.setCurrent_col(6);
                piece.setCurrent_row(10);
                piece.setImage(R.drawable.red_guard);
                piece.setClickedAndMovedImage(R.drawable.red_guard_move);
                break;
            case 15: piece.setCurrent_col(4);
                piece.setCurrent_row(10);
                piece.setImage(R.drawable.red_guard);
                piece.setClickedAndMovedImage(R.drawable.red_guard_move);
                break;
            case 16: piece.setCurrent_col(5);
                piece.setCurrent_row(10);
                piece.setImage(R.drawable.red_general);
                piece.setClickedAndMovedImage(R.drawable.red_general_move);
                break;
            case 17: piece.setCurrent_col(1);
                piece.setCurrent_row(4);
                piece.setImage(R.drawable.black_soldier);
                piece.setClickedAndMovedImage(R.drawable.black_soldier_move);
                break;
            case 18: piece.setCurrent_col(3);
                piece.setCurrent_row(4);
                piece.setImage(R.drawable.black_soldier);
                piece.setClickedAndMovedImage(R.drawable.black_soldier_move);
                break;
            case 19: piece.setCurrent_col(5);
                piece.setCurrent_row(4);
                piece.setImage(R.drawable.black_soldier);
                piece.setClickedAndMovedImage(R.drawable.black_soldier_move);
                break;
            case 20: piece.setCurrent_col(7);
                piece.setCurrent_row(4);
                piece.setImage(R.drawable.black_soldier);
                piece.setClickedAndMovedImage(R.drawable.black_soldier_move);
                break;
            case 21: piece.setCurrent_col(9);
                piece.setCurrent_row(4);
                piece.setImage(R.drawable.black_soldier);
                piece.setClickedAndMovedImage(R.drawable.black_soldier_move);
                break;

            case 22: piece.setCurrent_col(2);
                piece.setCurrent_row(3);
                piece.setImage(R.drawable.black_cannon);
                piece.setClickedAndMovedImage(R.drawable.black_cannon_move);
                break;
            case 23: piece.setCurrent_col(8);
                piece.setCurrent_row(3);
                piece.setImage(R.drawable.black_cannon);
                piece.setClickedAndMovedImage(R.drawable.black_cannon_move);
                break;
            case 24: piece.setCurrent_col(1);
                piece.setCurrent_row(1);
                piece.setImage(R.drawable.black_chariot);
                piece.setClickedAndMovedImage(R.drawable.black_chariot_move);
                break;
            case 25: piece.setCurrent_col(9);
                piece.setCurrent_row(1);
                piece.setImage(R.drawable.black_chariot);
                piece.setClickedAndMovedImage(R.drawable.black_chariot_move);
                break;
            case 26: piece.setCurrent_col(2);
                piece.setCurrent_row(1);
                piece.setImage(R.drawable.black_horse);
                piece.setClickedAndMovedImage(R.drawable.black_horse_move);
                break;
            case 27: piece.setCurrent_col(8);
                piece.setCurrent_row(1);
                piece.setImage(R.drawable.black_horse);
                piece.setClickedAndMovedImage(R.drawable.black_horse_move);
                break;
            case 28: piece.setCurrent_col(3);
                piece.setCurrent_row(1);
                piece.setImage(R.drawable.black_elephant);
                piece.setClickedAndMovedImage(R.drawable.black_elephant_move);
                break;
            case 29: piece.setCurrent_col(7);
                piece.setCurrent_row(1);
                piece.setImage(R.drawable.black_elephant);
                piece.setClickedAndMovedImage(R.drawable.black_elephant_move);
                break;
            case 30: piece.setCurrent_col(4);
                piece.setCurrent_row(1);
                piece.setImage(R.drawable.black_guard);
                piece.setClickedAndMovedImage(R.drawable.black_guard_move);
                break;
            case 31: piece.setCurrent_col(6);
                piece.setCurrent_row(1);
                piece.setImage(R.drawable.black_guard);
                piece.setClickedAndMovedImage(R.drawable.black_guard_move);
                break;
            case 32: piece.setCurrent_col(5);
                piece.setCurrent_row(1);
                piece.setImage(R.drawable.black_general);
                piece.setClickedAndMovedImage(R.drawable.black_general_move);
                break;
            default:
                throw new IllegalStateException("Unexpected value: " + piece.getId());
        }
    }
}
