server:
  port: 8088
db:
  port: 3306
  name: chinese_chess
  endpoint: localhost
  username: root
  password: rootroot
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
domain:
  path: http://${db.endpoint}:${db.port}
url:
  redirect:
    path: ${domain.path}
