server:
  port: 8088

db:
  port: 3306
  name: chinese_chess
  endpoint: localhost
  username: root
  password:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

domain:
  path: https://${db.endpoint}:${db.port}

url:
  redirect:
    path: ${domain.path}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    serverUrl: http://localhost:${server.port} # http://localhost:8088/swagger-ui/index.html
    title: Chinese Chess API Document
    version: 1.0.0
    description: Chinese chess Service API Docs
    serverName: Local Development Server
